# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0002_auto_20170104_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_eyeheight_baseline',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_eyeheight_current',
            field=models.IntegerField(),
        ),
    ]
