# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0004_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_eyeheight_baseline',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_eyeheight_current',
            field=models.IntegerField(null=True),
        ),
    ]
