# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0005_auto_20170104_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_eyeheight_baseline',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_eyeheight_current',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_photo_current',
        ),
        migrations.AddField(
            model_name='user',
            name='user_eye_height_baseline',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_eye_height_current',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
