# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0006_auto_20170105_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_eye_height_baseline',
            new_name='user_baseline_eyes_height',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_photo_baseline',
            new_name='user_baseline_photo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_eye_height_current',
            new_name='user_current_eyes_height',
        ),
    ]
