# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0007_auto_20170105_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_current_eyes_height',
        ),
        migrations.AddField(
            model_name='user',
            name='user_latest_eyes_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_baseline_eyes_height',
            field=models.IntegerField(null=True),
        ),
    ]
